# Generated by Django 5.1 on 2024-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('creat_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='utilisateursecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('password2', models.CharField(default=True, max_length=128)),
            ],
        ),
    ]
