# Generated by Django 5.1 on 2024-08-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_utilisateur_user_delete_utilisateursecond'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
