# Generated by Django 5.1 on 2024-08-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Genre', models.CharField(choices=[('h', 'Homme'), ('f', 'Femme')], max_length=30)),
                ('registration_number', models.CharField(max_length=20, null=True)),
                ('birth_date', models.DateField()),
                ('Classe', models.CharField(choices=[('terminale', 'terminale'), ('premier', 'premier'), ('second', 'second'), ('troisieme', 'troisieme'), ('quatrieme', 'quatrieme'), ('cinquieme', 'cinquieme')], max_length=15)),
                ('phone_number', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
