# Generated by Django 5.1 on 2024-08-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('h', 'Homme'), ('f', 'Femme')], max_length=2)),
                ('birth_date', models.DateField()),
                ('matiere', models.CharField(choices=[('Math', 'Math'), ('Physique', 'Physique'), ('EPS', 'EPS'), ('Anglais', 'Anglais'), ('SVT', 'SVT'), ('Philosophie', 'Philosophie'), ('Français', 'Français')], max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('vacant', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
            },
        ),
    ]
